package com.rei.chairlift;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.List;
import java.util.function.Predicate;

import org.junit.Test;

import com.google.common.collect.ImmutableMap;

public class ChairliftTest extends BaseTemplateTest {
    @Test
    public void testFilters() {
        ChairliftConfig globalConfig = new ChairliftConfig(false, ImmutableMap.of());
        Chairlift chairlift = new Chairlift(globalConfig);
        TemplateConfig config = new TemplateConfig(globalConfig);
        config.getIncludedFiles().add("**/*");
        config.getExcludedFiles().add("**/exclude");
        
        assertTrue(allMatch(chairlift.getCopyFilters(config), Paths.get("/README.md")));
        assertTrue(allMatch(chairlift.getCopyFilters(config), Paths.get("/foo/bar")));
        assertFalse(allMatch(chairlift.getCopyFilters(config), Paths.get("/foo/exclude")));
    }
    
    @Test
    public void canGenerateProject() throws Exception {
        ChairliftConfig globalConfig = new ChairliftConfig(false, ImmutableMap.of());
        
        Chairlift chairlift = new Chairlift(globalConfig);
        Path projectFolder = tmp.newFolder("project").toPath();
        
        chairlift.generate(getTestTemplateArtifact("simple-template"), projectFolder);
        
        printDir(projectFolder);
        
        Path readme = projectFolder.resolve("README.md");
        assertTrue(Files.exists(readme));
        String content = Files.readAllLines(readme).get(0);
        System.out.println(content);
        assertEquals("Welcome to project my-app! Generated by simple-template v1", content);
        
        Path appFile = projectFolder.resolve("my-app/MyApp.java");
        assertTrue(Files.exists(appFile));
    }
    
    private void printDir(Path dir) throws IOException {
        Files.walkFileTree(dir, new SimpleFileVisitor<Path>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                System.out.println(file);
                return FileVisitResult.CONTINUE;
            }
        });
    }

    private boolean allMatch(List<Predicate<Path>> copyFilters, Path file) {
        return copyFilters.stream().allMatch(p -> p.test(file));
    }
}
